### ISSUE TITLE
Problems accessing configurations' fields in upload strategy

### ISSUE THREAD

**Issue by xAlessandroC** [xAlessandroC/oteapi-ontokb-plugin#1]
# Brief explanation of the problem
I have errors in accessing the configuration fields of the upload strategy. In particular, I get the error **'AttrDict' object has no attribute 'datacache_config'**

 **Related to the 89ce60bdc2eae85d99abebec5ec3ad4a40edf85b repo version**

# Environment setup
1. Have a running OntoKB + OntoREC docker container. The relative docker-compose file can be found [here](https://gitlab.cc-asp.fraunhofer.de/ontotrans/ontotranscorecomponents/-/blob/master/docker-compose.yml)
2. Have a running oteapi-service docker container.
    - repo version: https://github.com/EMMC-ASBL/oteapi-services/commit/f71498a4638a9ecf2fec8b216f20cd26585b8390
    - add the following line to requirements.txt in order to install the ontokb-plugin:
oteapi-ontokb-plugin @ git+https://github.com/xAlessandroC/oteapi-ontokb-plugin@89ce60bdc2eae85d99abebec5ec3ad4a40edf85b
     - put full_ontology_inferred_remapped.rdf file in the project and add this line to the Dockerfile:
COPY full_ontology_inferred_remapped.rdf /app
3. Have otelib installed
### Steps to reproduce the error (1)
1. Create OTEClient
```
client = OTEClient('http://localhost:<YOUR OTEAPI PORT>')
```
2. Create an otelib dataresource filter
```
uploader = client.create_dataresource(
        accessUrl = "http://host.docker.internal:<YOUR ONTOREC PORT>",
        accessService = "datasource/ontokb_upload",
        configuration = {
            "database":"temp",
            "filename":"full_ontology_inferred_remapped.rdf",
            "fileConfig": {
                "downloadUrl":"file:///app/full_ontology_inferred_remapped.rdf",
                "mediaType":"application/json",
                "configuration":{
                    "text" : True,
                    "encoding" : "utf-8"
                }
            }
        }
    )
```
3. Create pipeline and get the result
```
totalpipe = uploader
totalpipe.get()
```

In the oteapi-service docker container log I get the error
```
File "/usr/local/lib/python3.9/site-packages/oteapi_ontokb_plugin/strategies/ontokb_upload.py", line 82, in get
    cache = DataCache(self.resource_config.configuration.datacache_config)
AttributeError: 'AttrDict' object has no attribute 'datacache_config'
```

**The error doesn't appear if I use oteapi-core v0.1.2 directly without otelib/oteapi-services**

```
StrategyFactory.load_strategies()

    config: "StrategyConfig" = OntoKBResourceUploadConfig(
        accessUrl = "http://host.docker.internal:8090",
        accessService = "datasource/ontokb_upload",
        configuration = {
            "database":"temp",
            "filename":"full_ontology_inferred_remapped.rdf",
            "fileConfig": {
                "downloadUrl":r"<path to local file>\full_ontology_inferred_remapped.rdf",
                "mediaType":"application/json",
                "configuration":{
                    "text" : True,
                    "encoding" : "utf-8"
                }
            }
        }
    )

    strategy = create_strategy(StrategyType.RESOURCE, config)
    output = strategy.get()
    print(output)
```
The ontology is correctly loaded in OntoKB

**Comment by xAlessandroC** [comment]
@CasperWA

**Comment by CasperWA** [comment]
I have found the issue.

We (well, to be fair, only I am to blame for this...) have changed the usage from the built-in `dataclasses` library and instead use the dataclasses from pydantic.
To change this you should change all instances:

```python
from dataclasses import dataclass
```

to:

```python
from pydantic.dataclasses import dataclass
```

There are some other changes related to this main change as well - I'll open a PR against the `feat/plugin-develop` branch if that's okay?

**Comment by xAlessandroC** [comment]
Thank you so much for your time and the PR. In the next days, I'll check the code and do the merge to see if the problem is solved!

**Comment by xAlessandroC** [comment]
I tried the plugin with your fixes and now it seems to work. I think I can close this issue and continue with the development
